### ISSUE TITLE
Forgot Password Functionality

### ISSUE THREAD

**Issue by brettclanton001** [brettclanton001/Dashous#7]
As a Dashous user
given that I have forgotten my password
I should be able to have it reset by clicking a link
because forgetting your password shouldn't lock you out of a service forever

**Comment by CraigWilliams** [comment]
Hey @brettclanton001, I'm working on this. I'll create a PR when I'm done.

**Comment by CraigWilliams** [comment]
Do you want to run Sidekiq for sending emails? I believe it is free to run a worker on Heroku now.

**Comment by brettclanton001** [comment]
I'm planning to use resque for background jobs, but I've used sidekiq before, I'll revisit using that as well.  Need to compare the communities again..

Will review this soon, thanks!

**Comment by CraigWilliams** [comment]
Resque is good. I actually prefer the dashboard in resque over the one in sidekiq.

**Comment by brettclanton001** [comment]
@CraigWilliams I had already started on a resque setup on another branch.  It's a high priority because I need more api calls for exchange rates on more currencies, and I need to introduce more email functionality ( like the one you just introduced ), especially for notifications when offers are created, accepted, etc.  So this will be running soon.

**Comment by brettclanton001** [comment]
Closing this, will have the functionality on Dashous.com soon :)
