### ISSUE TITLE
CircleCI or other automated test runner

### ISSUE THREAD

**Issue by CraigWilliams** [brettclanton001/Dashous#9]
Is this a feature you would like to have and if so, which service do you prefer?

**Comment by brettclanton001** [comment]
I've used Circle Ci in the past, and don't mind setting it up.  I guess I've been just working solo on this for a while and it's easy enough to run them locally.  But I think your point is that it would help others to contribute, and I would agree with that.

The free tier on CircleCi would be plenty of power for this project.  I'll set it up now.
